/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graavm;

import java.lang.reflect.InvocationTargetException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        App app = new App();

        System.out.println(app.getGreeting());
        System.out.println(App.class.getMethod("getGreeting").invoke(app));
        System.out.println(Class.forName("graavm.App").getMethod("getGreeting").invoke(app));
        System.out.println(Class.forName(args[0]).getMethod("getGreeting").invoke(app));
    }
}
